import React from "react";
import "../css/TermsOfService.css";

const TermsOfService = () => {
  return (
    <div
      className="container"
      style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        lineHeight: "2rem",
        textAlign: "left",
      }}
    >
      <h2 style={{ textAlign: "center", marginBottom: "50px" }}>
        Terms of Service
      </h2>
      <p>
        Our Terms of Service were last updated on September 20, 2022. Please
        read these terms and conditions carefully before using Our Service.
      </p>
      <h3>Interpretation and Definitions</h3>
      <h4>Interpretation</h4>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
      <h4>Definitions</h4>
      <p>For the purposes of these Terms of Service:</p>
      <ul>
        <li>
          “Account” means a unique account created for You to access our Service
          or parts of our Service.
        </li>
        <li>
          “Feedback” means feedback, innovations or suggestions sent by You
          regarding the attributes, performance or features of our Service.
        </li>
        <li>
          “Terms of Service” (also referred as "Terms") mean these Terms of
          Service that form the entire agreement between You and the Company
          regarding the use of the Service. This Terms of Service Agreement was
          generated by TermsFeed Terms of Service Generator.
        </li>
        <li>
          “You” means the individual accessing or using the Service, or the
          company, or other legal entity on behalf of which such individual is
          accessing or using the Service, as applicable.
        </li>
      </ul>
      <h3>Acknowledgment</h3>
      <p>
        These are the Terms of Service governing the use of this Service and the
        agreement that operates between You and the Company. These Terms of
        Service set out the rights and obligations of all users regarding the
        use of the Service.
      </p>
      <p>
        Your access to and use of the Service is conditioned on Your acceptance
        of and compliance with these Terms of Service. These Terms of Service
        apply to all visitors, users and others who access or use the Service.
      </p>
      <p>
        By accessing or using the Service You agree to be bound by these Terms
        of Service. If You disagree with any part of these Terms of Service then
        You may not access the Service.
      </p>
      <p>
        You represent that you are over the age of 18. The Company does not
        permit those under 18 to use the Service.
      </p>
      <p>
        Your access to and use of the Service is also conditioned on Your
        acceptance of and compliance with the Privacy Policy of the Company. Our
        Privacy Policy describes Our policies and procedures on the collection,
        use and disclosure of Your personal information when You use the
        Application or the Website and tells You about Your privacy rights and
        how the law protects You. Please read Our Privacy Policy carefully
        before using Our Service.
      </p>
      <h3>User Accounts</h3>
      <p>
        When You create an account with Us, You must provide Us information that
        is accurate, complete, and current at all times. Failure to do so
        constitutes a breach of the Terms, which may result in immediate
        termination of Your account on Our Service.
      </p>
      <p>
        You are responsible for safeguarding the password that You use to access
        the Service and for any activities or actions under Your password,
        whether Your password is with Our Service or a Third-Party Social Media
        Service.
      </p>
      <p>
        You agree not to disclose Your password to any third party. You must
        notify Us immediately upon becoming aware of any breach of security or
        unauthorized use of Your account.
      </p>
      <p>
        You may not use as a username the name of another person or entity or
        that is not lawfully available for use, a name or trademark that is
        subject to any rights of another person or entity other than You without
        appropriate authorization, or a name that is otherwise offensive, vulgar
        or obscene.
      </p>
    </div>
  );
};

export default TermsOfService;
